version: "3.7"
services: 

  db:
    image: mariadb:10
    container_name: wp-60sec-db
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    # command:
    # - --config.my-cnf /etc/.mysqld_exporter.cnf
    # - --collect.global_status
    # - --collect.info_schema.innodb_metrics
    # - --collect.auto_increment.columns
    # - --collect.info_schema.processlist
    # - --collect.binlog_size
    # - --collect.info_schema.tablestats
    # - --collect.global_variables
    # - --collect.info_schema.query_response_time
    # - --collect.info_schema.userstats
    # - --collect.info_schema.tables
    # - --collect.perf_schema.tablelocks
    # - --collect.perf_schema.file_events
    # - --collect.perf_schema.eventswaits
    # - --collect.perf_schema.indexiowaits
    # - --collect.perf_schema.tableiowaits 
    # - --collect.slave_status 
    # - --web.listen-address=0.0.0.0:9104
  
  wordpress-fpm:
    image: wordpress:5-fpm-alpine
    container_name: wp-60sec-fpm
    links:
      - db
    volumes:
      - wp_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
  
  nginx:
    image: nginx:alpine
    container_name: wp-60sec-nginx
    depends_on: 
      - wordpress-fpm
    ports:
      - 8085:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - wp_files:/var/www/html

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: always
    environment:
      TZ: "Europe/Moscow"

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"

  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter
    container_name: mysqld-exporter
    restart: unless-stopped
    ports:
     - 9104:9104
    command:
     - "--mysqld.username=${WORDPRESS_DB_USER}:${WORDPRESS_DB_PASSWORD}"
     - "--mysqld.address=${WORDPRESS_DB_HOST}:3306"

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"

volumes: 
  wp_files: 
